apiVersion: v1
kind: pod
metadata:
  name: test-vol
spec:
  containers:
  - image: coolgourav147/nginx-custom
    name: test-containers
    volumeMounts:
      - mountPath: /data
        name: first-volume
  volumes:
    - name: first-volume
      awsElasticBlockStore:
        volumeID: "vol-04b986e4dd5ba99c0"
        fsType: ext4
   